name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull build image (amd64)
        run: bash ./pull_docker.sh latest --platform linux/amd64 --no-retag

      - name: Build & test google-test-app
        uses: ./.github/actions/ubuntu-env-exec
        with:
          image: ksx0303x/ubuntu-env:latest
          command: >-
            cd /home/ubuntu/Shared/Applications/google-test-app
            && bash ./build.sh gtest
            && meson test -C build --print-errorlogs
